/**
 * Phase 5 — Manufacturing vertical actions.
 *
 * Migrated verbatim from the pre-Phase-5 `core/actionRegistry.ts`
 * `manufacturingActions` array (May 2026 surveyed: 57 actions in this
 * vertical, not counting the 4 cross-vertical creates in `shared.ts`
 * and the new triage entries in `triage.ts`).
 *
 * Note: `create_order` / `create_disinterment` / `create_urn_order`
 * are deliberately absent — they are covered by the universal
 * `wf_create_order` workflow which accepts natural-language input and
 * discriminates by product line. Keeping separate ACTION entries
 * would duplicate the workflow entry in the command bar.
 */

import type { ActionRegistryEntry } from "./types";

export const manufacturingActions: ActionRegistryEntry[] = [
  // ── Operations ────────────────────────────────────────────────
  {
    id: "schedule_delivery",
    title: "Schedule delivery",
    subtitle: "Open delivery scheduling",
    icon: "truck",
    kind: "action",
    keywords: ["schedule delivery", "new delivery", "delivery for"],
    roles: ["admin", "office", "driver"],
    vertical: "manufacturing",
    route: "/scheduling/new",
  },
  {
    id: "log_pour",
    title: "Log production pour",
    subtitle: "Record mold pour event",
    icon: "layers",
    kind: "action",
    keywords: ["log pour", "pour mold", "production pour", "poured"],
    roles: ["admin", "production"],
    vertical: "manufacturing",
    route: "/production/log-pour",
  },
  {
    id: "log_strip",
    title: "Log mold strip",
    subtitle: "Record strip event",
    icon: "check-square",
    kind: "action",
    keywords: ["log strip", "strip mold", "stripped"],
    roles: ["admin", "production"],
    vertical: "manufacturing",
    route: "/production/log-strip",
  },
  {
    id: "view_deliveries_today",
    title: "Deliveries today",
    icon: "calendar",
    kind: "navigate",
    keywords: ["deliveries today", "todays deliveries", "today delivery"],
    roles: ["admin", "office", "driver"],
    vertical: "manufacturing",
    route: "/scheduling?filter=today",
  },
  {
    id: "view_compliance_overdue",
    title: "Overdue compliance items",
    icon: "alert-triangle",
    kind: "navigate",
    keywords: ["overdue compliance", "compliance overdue", "whats overdue"],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/compliance?filter=overdue",
  },
  {
    id: "open_morning_briefing",
    title: "Morning briefing",
    subtitle: "Today's operational overview",
    icon: "sun",
    kind: "navigate",
    keywords: ["morning briefing", "briefing", "whats happening today"],
    roles: ["admin", "office", "production", "driver"],
    vertical: "manufacturing",
    route: "/",
  },
  {
    id: "call_customer",
    title: "Call customer",
    subtitle: "Open phone",
    icon: "phone",
    kind: "action",
    keywords: ["call", "phone", "contact"],
    roles: ["admin", "office", "driver"],
    vertical: "manufacturing",
  },

  // ── Primary nav ─────────────────────────────────────────────
  {
    id: "nav_orders",
    title: "Order Station",
    icon: "zap",
    kind: "navigate",
    keywords: ["go to orders", "open orders", "order station"],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/orders",
  },
  {
    id: "nav_scheduling",
    title: "Scheduling Board",
    icon: "calendar",
    kind: "navigate",
    keywords: ["go to scheduling", "scheduling board", "open scheduling"],
    roles: ["admin", "office", "driver"],
    vertical: "manufacturing",
    route: "/scheduling",
  },
  {
    id: "nav_compliance",
    title: "Compliance Hub",
    icon: "shield",
    kind: "navigate",
    keywords: ["go to compliance", "open compliance", "compliance hub"],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/compliance",
  },
  {
    id: "nav_production",
    title: "Production Board",
    icon: "layers",
    kind: "navigate",
    keywords: ["go to production", "production board", "open production"],
    roles: ["admin", "production"],
    vertical: "manufacturing",
    route: "/production",
  },
  {
    id: "nav_crm",
    title: "CRM",
    icon: "users",
    kind: "navigate",
    keywords: ["go to crm", "open crm", "customers", "funeral homes"],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/vault/crm",
  },

  // ── Disinterments ──────────────────────────────────────────
  {
    id: "nav_disinterments",
    title: "Disinterments",
    subtitle: "View and manage disinterment orders",
    icon: "clipboard-list",
    kind: "navigate",
    keywords: [
      "disinterment",
      "disinterments",
      "exhumation",
      "open disinterment",
      "disinterment order",
    ],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/compliance/disinterments",
  },

  // ── Financial reports (admin only) ─────────────────────────
  {
    id: "report_ar_aging",
    title: "AR Aging Report",
    subtitle: "Accounts receivable by age",
    icon: "bar-chart",
    kind: "navigate",
    keywords: [
      "ar aging",
      "accounts receivable",
      "aging report",
      "outstanding invoices",
      "overdue",
    ],
    roles: ["admin"],
    vertical: "manufacturing",
    route: "/ar/aging",
  },
  {
    id: "report_ap_aging",
    title: "AP Aging Report",
    subtitle: "Accounts payable by age",
    icon: "bar-chart",
    kind: "navigate",
    keywords: ["ap aging", "accounts payable", "bills aging"],
    roles: ["admin"],
    vertical: "manufacturing",
    route: "/ap/aging",
  },
  {
    id: "report_revenue",
    title: "Revenue Report",
    icon: "trending-up",
    kind: "navigate",
    keywords: [
      "revenue report",
      "sales report",
      "revenue by product",
      "revenue by customer",
      "monthly revenue",
    ],
    roles: ["admin"],
    vertical: "manufacturing",
    route: "/reports",
  },
  {
    id: "run_statements",
    title: "Run Monthly Statements",
    icon: "file-text",
    kind: "action",
    keywords: [
      "run statements",
      "monthly statements",
      "statements",
      "ar statements",
      "customer statements",
    ],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/ar/statements",
  },

  // ── Compliance submodules ──────────────────────────────────
  {
    id: "nav_safety",
    title: "Safety & OSHA",
    icon: "shield",
    kind: "navigate",
    keywords: [
      "safety",
      "osha",
      "safety programs",
      "written programs",
      "training matrix",
    ],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/safety",
  },
  {
    id: "nav_vehicles",
    title: "Vehicle & DOT",
    icon: "truck",
    kind: "navigate",
    keywords: [
      "vehicles",
      "dot",
      "fleet",
      "vehicle registry",
      "hut",
      "dot registration",
    ],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/compliance",
  },
  {
    id: "nav_npca",
    title: "NPCA Certification",
    icon: "award",
    kind: "navigate",
    keywords: [
      "npca",
      "plant certification",
      "npca audit",
      "concrete certification",
    ],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/compliance",
  },
  {
    id: "audit_prep",
    title: "Run Audit Prep",
    subtitle: "Generate compliance audit package",
    icon: "file-search",
    kind: "action",
    keywords: [
      "audit prep",
      "run audit prep",
      "compliance audit",
      "generate audit package",
      "audit report",
    ],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/compliance",
  },
  {
    id: "nav_incidents",
    title: "Safety Incidents",
    icon: "alert-triangle",
    kind: "navigate",
    keywords: ["incidents", "safety incident", "incident report", "osha 300"],
    roles: ["admin", "office", "production"],
    vertical: "manufacturing",
    route: "/safety/incidents",
  },
  {
    id: "create_incident",
    title: "Log safety incident",
    icon: "plus-circle",
    kind: "action",
    keywords: ["log incident", "new incident", "report incident"],
    roles: ["admin", "office", "production"],
    vertical: "manufacturing",
    route: "/safety/incidents/new",
  },
  {
    id: "nav_training",
    title: "Safety Training",
    icon: "book-open",
    kind: "navigate",
    keywords: ["training", "safety training", "osha training", "toolbox talks"],
    roles: ["admin", "office", "production"],
    vertical: "manufacturing",
    route: "/safety/training",
  },

  // ── Social Service Certificates ───────────────────────────
  {
    id: "nav_ss_certs",
    title: "Social Service Certificates",
    icon: "file-check",
    kind: "navigate",
    keywords: [
      "social service",
      "ss certificate",
      "social service certificate",
      "ss cert",
    ],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/social-service-certificates",
  },

  // ── Settings ──────────────────────────────────────────────
  {
    id: "settings_programs",
    title: "Program Settings",
    icon: "settings",
    kind: "navigate",
    keywords: [
      "programs",
      "wilbert programs",
      "program settings",
      "vault program",
      "urn program",
      "casket program",
    ],
    roles: ["admin"],
    vertical: "manufacturing",
    route: "/settings/programs",
  },
  {
    id: "settings_locations",
    title: "Location Settings",
    icon: "map-pin",
    kind: "navigate",
    keywords: [
      "locations",
      "location settings",
      "manage locations",
      "add location",
      "plants",
    ],
    roles: ["admin"],
    vertical: "manufacturing",
    route: "/settings/locations",
  },
  {
    id: "settings_team",
    title: "Team Settings",
    icon: "users",
    kind: "navigate",
    keywords: [
      "team",
      "users",
      "invite user",
      "manage team",
      "add user",
      "team settings",
    ],
    roles: ["admin"],
    vertical: "manufacturing",
    route: "/team",
  },
  {
    id: "settings_product_lines",
    title: "Product Lines",
    icon: "package",
    kind: "navigate",
    keywords: [
      "product lines",
      "extensions",
      "redi-rock",
      "wastewater",
      "activate product line",
    ],
    roles: ["admin"],
    vertical: "manufacturing",
    route: "/settings/product-lines",
  },
  {
    id: "settings_tax",
    title: "Tax Settings",
    icon: "percent",
    kind: "navigate",
    keywords: ["tax settings", "tax rates", "sales tax", "tax jurisdictions"],
    roles: ["admin"],
    vertical: "manufacturing",
    route: "/settings/tax",
  },
  {
    id: "settings_invoice",
    title: "Invoice Settings",
    icon: "file-text",
    kind: "navigate",
    keywords: ["invoice settings", "invoice template", "invoice design"],
    roles: ["admin"],
    vertical: "manufacturing",
    route: "/settings/invoice",
  },
  {
    id: "settings_email",
    title: "Email Settings",
    icon: "mail",
    kind: "navigate",
    keywords: ["email settings", "email config", "smtp", "platform email"],
    roles: ["admin"],
    vertical: "manufacturing",
    route: "/settings/email",
  },
  {
    id: "settings_call_intelligence",
    title: "Call Intelligence Settings",
    icon: "phone",
    kind: "navigate",
    keywords: ["call intelligence", "ringcentral", "phone integration"],
    roles: ["admin"],
    vertical: "manufacturing",
    route: "/settings/call-intelligence",
  },

  // ── Invoices ──────────────────────────────────────────────
  {
    id: "nav_invoices",
    title: "Invoices",
    icon: "file-text",
    kind: "navigate",
    keywords: ["invoices", "ar invoices", "open invoice", "invoice list"],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/ar/invoices",
  },
  {
    id: "review_invoices",
    title: "Review Invoices",
    subtitle: "Pending invoice approvals",
    icon: "check-square",
    kind: "navigate",
    keywords: ["review invoices", "draft invoices", "invoice review queue"],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/ar/invoices/review",
  },
  {
    id: "nav_payments",
    title: "Customer Payments",
    icon: "dollar-sign",
    kind: "navigate",
    keywords: ["payments", "customer payments", "ar payments"],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/ar/payments",
  },
  {
    id: "nav_quotes",
    title: "Quotes",
    icon: "file-text",
    kind: "navigate",
    keywords: ["quotes", "estimates"],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/ar/quotes",
  },

  // ── AP ────────────────────────────────────────────────────
  {
    id: "nav_bills",
    title: "Vendor Bills",
    icon: "file-text",
    kind: "navigate",
    keywords: ["bills", "vendor bills", "ap bills"],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/ap/bills",
  },
  {
    id: "nav_purchase_orders",
    title: "Purchase Orders",
    icon: "shopping-cart",
    kind: "navigate",
    keywords: ["purchase orders", "po", "pos"],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/ap/purchase-orders",
  },
  {
    id: "nav_vendor_payments",
    title: "Vendor Payments",
    icon: "dollar-sign",
    kind: "navigate",
    keywords: ["vendor payments", "ap payments", "pay vendor"],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/ap/payments",
  },

  // ── Products ──────────────────────────────────────────────
  {
    id: "nav_products",
    title: "Product Catalog",
    icon: "package",
    kind: "navigate",
    keywords: ["products", "product catalog", "catalog", "skus", "price list"],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/products",
  },

  // ── Knowledge base ────────────────────────────────────────
  {
    id: "nav_knowledge_base",
    title: "Knowledge Base",
    icon: "book-open",
    kind: "navigate",
    keywords: [
      "knowledge base",
      "knowledge",
      "docs",
      "documentation",
      "kb",
    ],
    roles: ["admin", "office", "production", "driver"],
    vertical: "manufacturing",
    route: "/knowledge-base",
  },

  // ── Urns (resale) ────────────────────────────────────────
  {
    id: "nav_urns",
    title: "Urn Catalog",
    icon: "package",
    kind: "navigate",
    keywords: ["urns", "urn catalog", "urn orders", "resale"],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/urns/catalog",
  },

  // ── Team ─────────────────────────────────────────────────
  {
    id: "nav_team",
    title: "Team",
    icon: "users",
    kind: "navigate",
    keywords: ["team", "employees", "staff", "team members", "personnel"],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/team",
  },

  // ── Spring burials ──────────────────────────────────────
  {
    id: "nav_spring_burials",
    title: "Spring Burials",
    icon: "calendar",
    kind: "navigate",
    keywords: ["spring burials", "spring burial list", "seasonal burials"],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/spring-burials",
  },

  // ── Transfers ───────────────────────────────────────────
  {
    id: "nav_transfers",
    title: "Transfers",
    icon: "repeat",
    kind: "navigate",
    keywords: ["transfers", "cross licensee", "licensee transfer"],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/transfers",
  },

  // ── Calls ───────────────────────────────────────────────
  {
    id: "nav_call_log",
    title: "Call Log",
    icon: "phone",
    kind: "navigate",
    keywords: ["call log", "calls", "recent calls", "phone history"],
    roles: ["admin", "office"],
    vertical: "manufacturing",
    route: "/calls",
  },

  // ── Agents ──────────────────────────────────────────────
  {
    id: "nav_agents",
    title: "Accounting Agents",
    icon: "bot",
    kind: "navigate",
    keywords: ["agents", "ai agents", "accounting agents"],
    roles: ["admin"],
    vertical: "manufacturing",
    route: "/agents",
  },
];
