"""Seed Workflow Arc Phase 8d.1 triage Intelligence prompt.

One prompt:
  - triage.safety_program_context_question

Uses Option A idempotent seed pattern (same as Phase 6 briefings,
Phase 8b cash receipts, Phase 8c accounting batch):
  - No existing prompt              → create + v1 active
  - Exactly 1 version matching      → no-op
  - Exactly 1 version differing     → deactivate v1 + create v2
  - Multiple versions (admin custom)→ skip with warning

Phase 8d.1 is the reconnaissance for AI-generation-with-approval
shape. The AI panel grounds in related entities built by
`_build_safety_program_related`:
  - safety_program_generation (the item being reviewed)
  - safety_training_topic (target topic, OSHA code, key points)
  - osha_scrape (regulatory source text snippet + scrape URL)
  - safety_program (prior version content, for year-over-year diff)
  - document (generated PDF download URL — inline per approved scope)

Run:
    cd backend && source .venv/bin/activate
    DATABASE_URL=<url> python scripts/seed_triage_phase8d1.py
"""

from __future__ import annotations

import logging
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sqlalchemy.orm import Session

from app.database import SessionLocal
from app.models.intelligence import IntelligencePrompt, IntelligencePromptVersion


logger = logging.getLogger(__name__)


_VARIABLE_SCHEMA = {
    "item_json": {"type": "string", "required": True},
    "user_question": {"type": "string", "required": True},
    "tenant_context": {"type": "string", "required": True},
    "related_entities_json": {"type": "string", "required": False},
}
_RESPONSE_SCHEMA = {
    "type": "object",
    "properties": {
        "answer": {"type": "string"},
        "confidence": {"type": "number"},
        "sources": {"type": "array"},
    },
    "required": ["answer", "confidence"],
}


@dataclass(frozen=True)
class PromptSpec:
    prompt_key: str
    display_name: str
    description: str
    system_prompt: str


_USER_TEMPLATE = "{{user_question}}"


_PROMPTS: list[PromptSpec] = [
    PromptSpec(
        prompt_key="triage.safety_program_context_question",
        display_name="Triage — Safety Program context question",
        description=(
            "Answer safety trainer + compliance officer questions "
            "about an AI-generated safety program under approval "
            "triage. Grounds in the generation metadata + target "
            "OSHA topic + scraped regulatory source + prior program "
            "version (for year-over-year diff) + the generated PDF. "
            "First migration-arc queue exercising AI-assisted review "
            "of AI-generated artifacts."
        ),
        system_prompt=(
            "You help a safety trainer or compliance officer decide "
            "whether to approve an AI-generated monthly safety "
            "program. The program was generated by Claude Sonnet from "
            "scraped OSHA regulation text + a safety-training topic "
            "definition + company context. Your job is to help the "
            "human reviewer catch anything Claude missed or got "
            "wrong — regulatory gaps, industry-inappropriate "
            "language, inconsistencies with last year's version, "
            "sections that need extra scrutiny.\n\n"
            "Ground every answer in the related entities provided. "
            "These include:\n"
            "  - safety_program_generation (metadata: topic, OSHA "
            "code, generation timestamp, model, token usage)\n"
            "  - safety_training_topic (target topic title, "
            "osha_standard, key_points, is_high_risk flag)\n"
            "  - osha_scrape (text_snippet up to 500 chars + the "
            "scrape_url for the authoritative OSHA page)\n"
            "  - safety_program (prior-version content_snippet up "
            "to 1000 chars, when a prior approval exists for the "
            "same OSHA standard code — use this for \"what's "
            "changing\" questions)\n"
            "  - document (generated PDF download URL + title)\n\n"
            "VERTICAL-APPROPRIATE TERMINOLOGY: the tenant is a "
            "PRECAST CONCRETE / BURIAL VAULT MANUFACTURER. Reference "
            "precast-specific hazards (rebar handling, vault pour, "
            "demolding, chemical admixtures, forklift + vault "
            "maneuvering, silica dust from cutting cured concrete) "
            "when they're relevant. Do NOT invent OSHA numbers or "
            "citations not present in the osha_scrape text_snippet; "
            "cite what's there or say you'd need to check the full "
            "standard.\n\n"
            "COMPLIANCE DISCIPLINE: if a reviewer asks \"are there "
            "OSHA requirements I should verify?\", ground your "
            "answer in the topic's key_points + the osha_scrape "
            "text_snippet. If the snippet doesn't cover a specific "
            "area the reviewer is asking about, say \"the snippet "
            "doesn't cover this — recommend reviewing the full "
            "standard at <scrape_url>\" rather than inventing "
            "requirements. Regulatory compliance is an area where "
            "hallucination causes legal exposure.\n\n"
            "For \"what's changing from last year\" questions, "
            "compare the generation's current state against the "
            "prior_version content_snippet when one is provided. If "
            "no prior version exists, explicitly say \"this is the "
            "first program for this OSHA standard under review.\"\n\n"
            "Return JSON with `answer` (string), `confidence` "
            "(0.0-1.0), `sources` (array of entity references, "
            "each like `{\"entity_type\": \"safety_training_topic\", "
            "\"entity_id\": \"...\"}` or similar).\n\n"
            "Triage item: {{item_json}}\n"
            "Related entities: {{related_entities_json}}\n"
            "Tenant: {{tenant_context}}"
        ),
    ),
]


def _matches(version: IntelligencePromptVersion, spec: PromptSpec) -> bool:
    return (
        version.system_prompt == spec.system_prompt
        and version.user_template == _USER_TEMPLATE
    )


def _create_version(
    db: Session,
    prompt: IntelligencePrompt,
    spec: PromptSpec,
    version_number: int,
    changelog: str,
) -> IntelligencePromptVersion:
    version = IntelligencePromptVersion(
        prompt_id=prompt.id,
        version_number=version_number,
        system_prompt=spec.system_prompt,
        user_template=_USER_TEMPLATE,
        variable_schema=_VARIABLE_SCHEMA,
        response_schema=_RESPONSE_SCHEMA,
        model_preference="simple",
        temperature=0.3,
        max_tokens=1024,
        force_json=True,
        supports_streaming=False,
        supports_tool_use=False,
        status="active",
        changelog=changelog,
        activated_at=datetime.now(timezone.utc),
    )
    db.add(version)
    return version


def seed_one(db: Session, spec: PromptSpec) -> dict[str, int]:
    stats = {"created": 0, "updated": 0, "noop": 0, "skipped_custom": 0}

    prompt = (
        db.query(IntelligencePrompt)
        .filter(
            IntelligencePrompt.company_id.is_(None),
            IntelligencePrompt.prompt_key == spec.prompt_key,
        )
        .first()
    )
    if prompt is None:
        prompt = IntelligencePrompt(
            company_id=None,
            prompt_key=spec.prompt_key,
            display_name=spec.display_name,
            description=spec.description,
            domain="triage",
        )
        db.add(prompt)
        db.flush()
        _create_version(
            db, prompt, spec, version_number=1,
            changelog=f"Phase 8d.1 seed — {spec.prompt_key}.",
        )
        db.commit()
        stats["created"] = 1
        return stats

    versions = (
        db.query(IntelligencePromptVersion)
        .filter(IntelligencePromptVersion.prompt_id == prompt.id)
        .all()
    )
    if len(versions) > 1:
        logger.warning(
            "Prompt %s has %d versions — admin customization in flight. "
            "Skipping platform update.",
            spec.prompt_key,
            len(versions),
        )
        stats["skipped_custom"] = 1
        return stats
    if len(versions) == 1:
        existing = versions[0]
        if _matches(existing, spec):
            stats["noop"] = 1
            return stats
        existing.status = "retired"
        db.flush()
        next_version_number = (existing.version_number or 1) + 1
        _create_version(
            db, prompt, spec, version_number=next_version_number,
            changelog=(
                f"Phase 8d.1 re-seed — platform update to "
                f"{spec.prompt_key}."
            ),
        )
        db.commit()
        stats["updated"] = 1
        return stats

    _create_version(
        db, prompt, spec, version_number=1,
        changelog=(
            f"Phase 8d.1 seed — adding v1 to existing empty prompt "
            f"{spec.prompt_key}."
        ),
    )
    db.commit()
    stats["created"] = 1
    return stats


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    totals = {"created": 0, "updated": 0, "noop": 0, "skipped_custom": 0}
    db = SessionLocal()
    try:
        for spec in _PROMPTS:
            stats = seed_one(db, spec)
            for k, v in stats.items():
                totals[k] = totals.get(k, 0) + v
            verb = next(
                (k for k, v in stats.items() if v), "unchanged"
            )
            logger.info("  %s  %s", spec.prompt_key, verb)
    finally:
        db.close()
    logger.info(
        "Phase 8d.1 seed totals: created=%d updated=%d noop=%d skipped_custom=%d",
        totals["created"], totals["updated"], totals["noop"],
        totals["skipped_custom"],
    )


if __name__ == "__main__":
    main()
