"""Cross-tenant document sharing service — Phase D-6.

This is the single entry point for sharing canonical Documents across
tenant boundaries. Every ad-hoc cross-tenant mechanism (statement PDFs
emailed as attachments, delivery confirmations exposed via VaultItems,
etc.) gets migrated to this service so there's one grant/revoke/audit
surface for the whole platform.

Permission model:
- Grant requires an ACTIVE PlatformTenantRelationship between owner
  and target (either direction — relationships are logically
  bidirectional from a sharing perspective). If no relationship
  exists, the UI offers "Request relationship" but grant creation
  itself fails with 403.
- Revocation is future-access-only. Previously-downloaded copies are
  outside our control.
- Re-granting a previously-revoked share creates a new row (audit
  trail stays linear per-row).

The service is the ONLY way `document_shares` rows should be created
or modified — there are no direct model mutations expected anywhere
else in the codebase. The audit log (`document_share_events`) is
append-only by contract.
"""

from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import and_, or_
from sqlalchemy.orm import Session

from app.models.canonical_document import Document
from app.models.document_share import DocumentShare, DocumentShareEvent
from app.models.document_share_read import DocumentShareRead
from app.models.platform_tenant_relationship import (
    PlatformTenantRelationship,
)

logger = logging.getLogger(__name__)


class SharingError(Exception):
    """Share operation rejected — invalid state, missing relationship,
    permission denied, etc. HTTP-friendly: carries `http_status`."""

    def __init__(self, message: str, *, http_status: int = 400) -> None:
        super().__init__(message)
        self.http_status = http_status


# ── Relationship precondition ────────────────────────────────────────


def has_active_relationship(
    db: Session, tenant_a: str, tenant_b: str
) -> bool:
    """Is there an active PlatformTenantRelationship between these two
    tenants in either direction?"""
    if tenant_a == tenant_b:
        # A tenant "sharing" with itself is a no-op we treat as allowed —
        # but see enforce_grant_preconditions which rejects self-shares.
        return True
    q = db.query(PlatformTenantRelationship).filter(
        PlatformTenantRelationship.status == "active",
        or_(
            and_(
                PlatformTenantRelationship.tenant_id == tenant_a,
                PlatformTenantRelationship.supplier_tenant_id == tenant_b,
            ),
            and_(
                PlatformTenantRelationship.tenant_id == tenant_b,
                PlatformTenantRelationship.supplier_tenant_id == tenant_a,
            ),
        ),
    )
    return db.query(q.exists()).scalar() is True


# ── Audit events ─────────────────────────────────────────────────────


def _record_event(
    db: Session,
    *,
    share: DocumentShare,
    event_type: str,
    actor_user_id: str | None = None,
    actor_company_id: str | None = None,
    ip_address: str | None = None,
    meta: dict[str, Any] | None = None,
) -> DocumentShareEvent:
    ev = DocumentShareEvent(
        id=str(uuid.uuid4()),
        share_id=share.id,
        document_id=share.document_id,
        event_type=event_type,
        actor_user_id=actor_user_id,
        actor_company_id=actor_company_id,
        ip_address=ip_address,
        meta_json=meta or {},
    )
    db.add(ev)
    return ev


# ── Grant + revoke ───────────────────────────────────────────────────


def grant_share(
    db: Session,
    *,
    document: Document,
    target_company_id: str,
    granted_by_user_id: str | None,
    reason: str | None = None,
    source_module: str | None = None,
    enforce_relationship: bool = True,
) -> DocumentShare:
    """Grant `target_company_id` read access to `document`.

    Args:
        document: canonical Document owned by some tenant
        target_company_id: tenant receiving access
        granted_by_user_id: whoever authorized the share (for audit)
        reason: human-readable label shown in the target's inbox
        source_module: which service created the share (e.g.
            "statement_pdf_service" for auto-created shares vs
            "admin.documents_v2" for manual admin grants)
        enforce_relationship: if True (default), requires an active
            PlatformTenantRelationship between owner and target. Auto-
            created shares from migrated document generators MAY pass
            False only when the sharing is structurally implied by the
            generator (e.g. a statement generated BY the owner FOR the
            target customer — the target is by definition in the
            owner's customer network).

    Raises:
        SharingError(403) if enforce_relationship and no relationship exists
        SharingError(400) if target == owner
        SharingError(409) if an active share already exists for this pair
    """
    if target_company_id == document.company_id:
        raise SharingError(
            "Cannot share a document with its owner tenant",
            http_status=400,
        )

    if enforce_relationship and not has_active_relationship(
        db, document.company_id, target_company_id
    ):
        raise SharingError(
            "No active PlatformTenantRelationship between owner and "
            "target. Request a relationship before sharing.",
            http_status=403,
        )

    # Check for existing active share (partial unique index will also
    # enforce this at DB level, but we want a clean error message)
    existing = (
        db.query(DocumentShare)
        .filter(
            DocumentShare.document_id == document.id,
            DocumentShare.target_company_id == target_company_id,
            DocumentShare.revoked_at.is_(None),
        )
        .first()
    )
    if existing is not None:
        raise SharingError(
            f"An active share already exists for this document + target "
            f"(share_id={existing.id}). Revoke it first if you want to "
            f"recreate with new parameters.",
            http_status=409,
        )

    share = DocumentShare(
        id=str(uuid.uuid4()),
        document_id=document.id,
        owner_company_id=document.company_id,
        target_company_id=target_company_id,
        permission="read",
        reason=reason,
        granted_by_user_id=granted_by_user_id,
        source_module=source_module,
    )
    db.add(share)
    db.flush()
    _record_event(
        db,
        share=share,
        event_type="granted",
        actor_user_id=granted_by_user_id,
        actor_company_id=document.company_id,
        meta={
            "reason": reason,
            "source_module": source_module,
            "enforce_relationship": enforce_relationship,
        },
    )

    # V-1d: Notify target tenant admins that a new document is in
    # their inbox. Fan-out so any admin of the target tenant sees the
    # unread badge; each admin's row links to the canonical document
    # detail page. Best-effort — wrapped so notification failures
    # never block a grant.
    try:
        from app.services import notification_service

        doc_title = (document.title or "Untitled document").strip()
        notification_service.notify_tenant_admins(
            db,
            company_id=target_company_id,
            title=f"New shared document: {doc_title[:120]}",
            message=(
                f"A document has been shared with your organization"
                + (f" — {reason}" if reason else ".")
            ),
            type="info",
            category="share_granted",
            link=f"/vault/documents/{document.id}",
            actor_id=granted_by_user_id,
            source_reference_type="document",
            source_reference_id=document.id,
        )
    except Exception:  # pragma: no cover — best-effort notify
        logger.exception(
            "share_granted notification fan-out failed "
            "(document_id=%s target_company_id=%s)",
            document.id,
            target_company_id,
        )

    return share


def revoke_share(
    db: Session,
    *,
    share: DocumentShare,
    revoked_by_user_id: str | None,
    revoke_reason: str | None = None,
) -> DocumentShare:
    """Set `revoked_at` on a share. Future `visible_to()` queries will
    exclude it. Previously-downloaded copies are NOT recallable — this
    is explicit in the API description + UI copy."""
    if share.revoked_at is not None:
        raise SharingError(
            "Share is already revoked", http_status=409
        )
    now = datetime.now(timezone.utc)
    share.revoked_at = now
    share.revoked_by_user_id = revoked_by_user_id
    share.revoke_reason = revoke_reason
    _record_event(
        db,
        share=share,
        event_type="revoked",
        actor_user_id=revoked_by_user_id,
        actor_company_id=share.owner_company_id,
        meta={"reason": revoke_reason},
    )
    return share


def record_access(
    db: Session,
    *,
    share: DocumentShare,
    actor_user_id: str | None,
    actor_company_id: str | None,
    ip_address: str | None = None,
    event_type: str = "accessed",
) -> DocumentShareEvent:
    """Record that a target tenant accessed (viewed or downloaded) the
    shared document. Called from read-path endpoints on document
    access; does NOT mutate the share row."""
    return _record_event(
        db,
        share=share,
        event_type=event_type,
        actor_user_id=actor_user_id,
        actor_company_id=actor_company_id,
        ip_address=ip_address,
    )


# ── Listing / lookup ─────────────────────────────────────────────────


def get_share(db: Session, share_id: str) -> DocumentShare | None:
    return db.query(DocumentShare).filter_by(id=share_id).first()


def get_active_share(
    db: Session, document_id: str, target_company_id: str
) -> DocumentShare | None:
    """Find an active share for a specific (doc, target) pair."""
    return (
        db.query(DocumentShare)
        .filter(
            DocumentShare.document_id == document_id,
            DocumentShare.target_company_id == target_company_id,
            DocumentShare.revoked_at.is_(None),
        )
        .first()
    )


def list_outgoing_shares(
    db: Session,
    *,
    owner_company_id: str,
    document_id: str | None = None,
    include_revoked: bool = False,
    limit: int = 100,
    offset: int = 0,
) -> list[DocumentShare]:
    """Shares originated BY `owner_company_id`."""
    q = db.query(DocumentShare).filter(
        DocumentShare.owner_company_id == owner_company_id
    )
    if document_id:
        q = q.filter(DocumentShare.document_id == document_id)
    if not include_revoked:
        q = q.filter(DocumentShare.revoked_at.is_(None))
    return (
        q.order_by(DocumentShare.granted_at.desc())
        .offset(offset)
        .limit(limit)
        .all()
    )


def list_incoming_shares(
    db: Session,
    *,
    target_company_id: str,
    document_type: str | None = None,
    include_revoked: bool = False,
    limit: int = 100,
    offset: int = 0,
) -> list[DocumentShare]:
    """Shares WHERE `target_company_id` is the recipient (the 'inbox')."""
    q = (
        db.query(DocumentShare)
        .join(Document, Document.id == DocumentShare.document_id)
        .filter(DocumentShare.target_company_id == target_company_id)
    )
    if document_type:
        q = q.filter(Document.document_type == document_type)
    if not include_revoked:
        q = q.filter(DocumentShare.revoked_at.is_(None))
    return (
        q.order_by(DocumentShare.granted_at.desc())
        .offset(offset)
        .limit(limit)
        .all()
    )


def list_events_for_share(
    db: Session, share_id: str, *, limit: int = 100, offset: int = 0
) -> list[DocumentShareEvent]:
    return (
        db.query(DocumentShareEvent)
        .filter(DocumentShareEvent.share_id == share_id)
        .order_by(DocumentShareEvent.created_at.desc())
        .offset(offset)
        .limit(limit)
        .all()
    )


# ── Convenience: auto-share for generator paths ──────────────────────


def ensure_share(
    db: Session,
    *,
    document: Document,
    target_company_id: str,
    reason: str | None,
    source_module: str,
    granted_by_user_id: str | None = None,
    enforce_relationship: bool = False,
) -> DocumentShare:
    """Idempotent variant used by migrated generator paths.

    If an active share already exists for (document, target), return
    it. Otherwise grant a new one. Used by:
      - statement_pdf_service — auto-share to the statement's customer
      - delivery service — auto-share delivery confirmation to FH
      - legacy_vault_print_service — auto-share to the manufacturer
      - etc.

    `enforce_relationship=False` by default because these auto-shares
    are structurally implied by the generator (a statement sent by
    tenant A to customer B means A↔B have an implicit business
    relationship even if they haven't explicitly set up a
    PlatformTenantRelationship yet).
    """
    existing = get_active_share(
        db, document.id, target_company_id
    )
    if existing is not None:
        return existing
    return grant_share(
        db,
        document=document,
        target_company_id=target_company_id,
        granted_by_user_id=granted_by_user_id,
        reason=reason,
        source_module=source_module,
        enforce_relationship=enforce_relationship,
    )


# ── Phase D-8: per-user inbox read tracking ─────────────────────────
#
# A share's "read" state is per-user, not per-tenant — two admins on
# the same tenant work through the same inbox independently. First-read
# wins; re-reading never un-marks. Delete-share cascades to these rows
# via FK; we keep them otherwise for the "read before revocation"
# audit view.


def mark_share_read(
    db: Session,
    *,
    share_id: str,
    user_id: str,
) -> DocumentShareRead:
    """Idempotent: returns the existing row if already read, else
    inserts a new one. The read_at timestamp reflects FIRST read."""
    existing = (
        db.query(DocumentShareRead)
        .filter(
            DocumentShareRead.share_id == share_id,
            DocumentShareRead.user_id == user_id,
        )
        .first()
    )
    if existing is not None:
        return existing
    row = DocumentShareRead(
        share_id=share_id,
        user_id=user_id,
        read_at=datetime.now(timezone.utc),
    )
    db.add(row)
    db.commit()
    db.refresh(row)
    return row


def get_read_share_ids(
    db: Session,
    *,
    user_id: str,
    share_ids: list[str] | None = None,
) -> dict[str, datetime]:
    """Return {share_id: read_at} for shares this user has read.

    If `share_ids` is given, scope the query to that subset — the
    common case when rendering a filtered inbox page.
    """
    q = db.query(
        DocumentShareRead.share_id, DocumentShareRead.read_at
    ).filter(DocumentShareRead.user_id == user_id)
    if share_ids:
        q = q.filter(DocumentShareRead.share_id.in_(share_ids))
    return {row.share_id: row.read_at for row in q.all()}


def mark_all_incoming_read(
    db: Session,
    *,
    target_company_id: str,
    user_id: str,
) -> int:
    """Mark every currently-active incoming share for this tenant as
    read for this user. Returns the number of NEW rows inserted
    (already-read shares are skipped)."""
    active_share_ids = [
        s.id
        for s in db.query(DocumentShare.id)
        .filter(
            DocumentShare.target_company_id == target_company_id,
            DocumentShare.revoked_at.is_(None),
        )
        .all()
    ]
    if not active_share_ids:
        return 0
    already_read = set(
        get_read_share_ids(
            db, user_id=user_id, share_ids=active_share_ids
        ).keys()
    )
    now = datetime.now(timezone.utc)
    inserted = 0
    for sid in active_share_ids:
        if sid in already_read:
            continue
        db.add(
            DocumentShareRead(share_id=sid, user_id=user_id, read_at=now)
        )
        inserted += 1
    if inserted:
        db.commit()
    return inserted
